---
name: Publish docs to staging website (for PR)

on:
  pull_request:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_primary_docs:
    name: Build primary documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main docs repo repository and build.
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "19"

      - name: Install NPM dependencies
        run: npm install --prefer-dedupe

      - name: Build Docusaurus website
        env:
          DOCUSAURUS_URL: https://dfhx9f55j8eg5.cloudfront.net/
          DOCUSAURUS_BASE_URL: /how-to/pr/${{github.event.number}}/
        run: npm run build

      - name: Upload primary docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: primary_docs
          path: build

  copy_schema_into_docs_and_deploy:
    needs:
      - build_primary_docs
    runs-on: ubuntu-latest
    steps:
      - name: Download primary docs
        uses: actions/download-artifact@v4
        with:
          name: primary_docs

      - name: Fetch AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::207370808101:role/Overture_GitHub_schema_Publish_Docs_Staging
          aws-region: us-east-2

      - name: Copy Docusaurus website to staging bucket how-to/pr/${{github.event.number}}/
        run: |
          aws --region us-east-2 s3 sync --delete --storage-class INTELLIGENT_TIERING . s3://overture-schema-docs-static-staging-us-east-2/how-to/pr/${{github.event.number}}

      - name: Purge CDN cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3L106P8HVBE9L --paths "/how-to/pr/${{github.event.number}}/*"
