---
name: Build the how-to pages with docusaurus

on:
  push:
    branches: [main]

  # Allow running from the actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build_schema_reference_docs:
    name: Build the schema reference documentation from `schema`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout schema repo
        uses: actions/checkout@v3
        with:
          repository: OvertureMaps/schema
          ref: main
          sparse-checkout: |
            docusaurus
            schema
            examples

      - name: Install NPM dependencies
        run: cd docusaurus && npm install

      - name: Build the schema reference documentation pages
        env:
          DOCUSAURUS_URL: docs.overturemaps.org
          DOCUSAURUS_BASE_URL: schema/
        run: cd docusaurus && npm run build

      - name: Upload schema reference docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema_reference_docs
          path: docusaurus/build

  publish:
    if: github.repository == 'overturemaps/docs'
    runs-on: ubuntu-latest
    needs: build_schema_reference_docs
    steps:
      - name: Check out the docs repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install NPM dependencies
        run: npm install

      - name: Build Docusaurus Pages ðŸ”§
        run: npm run build

      # Download the schema-reference docs into `build/schema`
      - name: Download schema reference docs
        uses: actions/download-artifact@v4
        with:
          name: schema_reference_docs
          path: build/schema/

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
